### ISSUE TITLE
スムーズスクロールの実装をどうやって実装するか?

### ISSUE THREAD

**Issue by bake0937** [YamadaLP/LP2#5]
スムーズスクロールの実装をどうやって実装するか?
JS?CSS?

**Comment by popmac** [comment]
jQueryのプラグインですかね...

**Comment by bake0937** [comment]
なるほど!
例えばこれですか?
http://phiary.me/jquery-page-link-smooth-scroll/

**Comment by popmac** [comment]
僕もこれを自分のアプリで使いました(笑)

**Comment by bake0937** [comment]
実装するとしたらこれでやりましょうか

**Comment by popmac** [comment]
了解です！

**Comment by bake0937** [comment]
了解です!closeします!
